### ISSUE TITLE
results on the LEVIR-CD

### ISSUE THREAD

**Issue by process852** [ggsDing/SAM-CD#10]
Thank you very much for your excellent work，

I found that I could not achieve the expected results of the paper when reproducing the code results. May I ask if there are any issues with my reproduction process？

```python
args = {
    'train_batch_size': 4,
    'val_batch_size': 4,
    'lr': 0.1,
    'epochs': 50,
    'gpu': True,
    'dev_id': 0,
    'multi_gpu': None,  #"0,1,2,3",
    'weight_decay': 5e-4,
    'momentum': 0.9,
    'print_freq': 50,
    'predict_step': 5,
    'crop_size': 512,
    'pred_dir': os.path.join(working_path, 'results', DATA_NAME),
    'chkpt_dir': os.path.join(working_path, 'checkpoints', DATA_NAME),
    'log_dir': os.path.join(working_path, 'logs', DATA_NAME, NET_NAME),
    'load_path': os.path.join(working_path, 'checkpoints', DATA_NAME, 'xxx.pth')}
```
```
python train_SAM_CD.py
```

* reproduce results:
![image](https://github.com/ggsDing/SAM-CD/assets/62278179/7d6d408e-1c78-4d71-b994-6c7d9563f6e5)

* paper results
![image](https://github.com/ggsDing/SAM-CD/assets/62278179/8fe07a03-4704-46ae-90bb-74395974ec52)

**Comment by sijie-Xu** [comment]
![1704182841534](https://github.com/ggsDing/SAM-CD/assets/122505422/8fdc93b9-57d5-4eae-a2a0-d1f88d8abd27) me too

**Comment by ggsDing** [comment]
> ![1704182841534](https://private-user-images.githubusercontent.com/122505422/293649413-8fdc93b9-57d5-4eae-a2a0-d1f88d8abd27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxOTE2NDksIm5iZiI6MTcwNDE5MTM0OSwicGF0aCI6Ii8xMjI1MDU0MjIvMjkzNjQ5NDEzLThmZGM5M2I5LTU3ZDUtNGVhZS1hMmEwLWQxZjg4ZDhhYmQyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQxMDI5MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNzkzNDU3ZjJlZTdhZDExMGQwODAyYWU1ZWZkM2UxZWRlOWFkNTdkMmVhMTIzYzczNjdmZTlmNjE5NGRkNGVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.860H_2IUoGZag2QUCBBdgHSC8OVZEH99G9GSypkc0g4) me too

This are the results on the validation set. The results in the paper are obtained on the test set.
Please first run 'Pred_CD.py', then using the evaluation codes to obtain the metrics.
