### ISSUE TITLE
Have you tried training with mobile-sam? 

### ISSUE THREAD

**Issue by sijie-Xu** [ggsDing/SAM-CD#12]
Have you tried using mobile-sam in Ultralytics? Does it support access to low-level features? I've noticed that the training process is quite lengthy with a large dataset. Currently, I'm unsure if mobile-sam can improve training efficiency compared to fastsam.

**Comment by ggsDing** [comment]
Hi. I have not tried this yet. I may try mobileSAM and efficientSAM and see if there are possible improvements.
If you are interested, you can also try and share the results.

**Comment by DingLei14** [comment]
> Have you tried using mobile-sam in Ultralytics? Does it support access to low-level features? I've noticed that the training process is quite lengthy with a large dataset. Currently, I'm unsure if mobile-sam can improve training efficiency compared to fastsam.

I have added support to efficientSAM. You are welcome to check: https://github.com/ggsDing/SAM-CD/blob/main/models/effSAM_CD.py
