### ISSUE TITLE
Dataset issue, hello , I wanna know where I can get the WHU-CD dataset. Could you please offer a Link?

### ISSUE THREAD

**Issue by JoeNumberOne** [ggsDing/SAM-CD#13]
Since I can find the LEVIR-CD Dataset, I wanna use the other dataset . But I can not find it .

**Comment by ggsDing** [comment]
Hi. I have summarized some dataset links. Please see the updated repository page.

**Comment by JoeNumberOne** [comment]
Thanks for reply,but the [WHU-CD](https://study.rsgis.whu.edu.cn/pages/download/) dataset, I can not open. Just like this
![image](https://github.com/ggsDing/SAM-CD/assets/34960932/d94c8fa0-f3af-4116-9393-70a227171f5e)
