### ISSUE TITLE
指标

### ISSUE THREAD

**Issue by JXBBBBB** [ggsDing/SAM-CD#15]
博主您好，为啥我按照你提供的代码库，最后训练出来的LEVIR，测试集只有91不到啊(变化区域的F1)

**Comment by ggsDing** [comment]
arxiv版本写错了，95应该是mF1，F1是91.46。

**Comment by JXBBBBB** [comment]
好的，这个代码库看着像BiSRNet的，我也一直在用，哈哈。还是非常感谢博主，数据加载部分提供的随机裁剪是个不错的思路。
