### ISSUE TITLE
请问SAM可以做SCD任务吗

### ISSUE THREAD

**Issue by Gchang9** [ggsDing/SAM-CD#17]

**Comment by ggsDing** [comment]
可以，但是直接做精度不高，因为SAM-CD 中可训练的模型参数较少。需进一步优化网络，或结合其他视觉基础模型

**Comment by ggsDing** [comment]
可以，但是直接做精度不高，因为SAM-CD 中可训练的模型参数较少。需进一步优化网络，或结合其他视觉基础模型
