### ISSUE TITLE
code about pred_CD & eval_CD when classic CD training

### ISSUE THREAD

**Issue by zhangda1018** [ggsDing/SAM-CD#18]
Hi, firstly a nice work!
I wanna to ask when I just use classic CD training: `python train_CD.py` , how to change `pred_CD.py` and `eval_CD.py`?
Can you provide another version?
Thanks a lot!

**Comment by ggsDing** [comment]
Hi. You can simply modify line 174 in pred_CD.py:
`output, _, _ = net(tensorA, tensorB)`
change it into:
`output = net(tensorA, tensorB)`

for eval_CD.py it is irrelevant to the prediction codes. Simply set the prediction path correct and it will work.

**Comment by zhangda1018** [comment]
Thanks!
