### ISSUE TITLE
train code with SAM

### ISSUE THREAD

**Issue by zhangda1018** [ggsDing/SAM-CD#19]
Hi there, sorry to bother you again!
Recently I'm replicating you model. I want to ask how to perform SAM with your model instead of FastSAM. Can you provide an instruction?
My mail is 1040676492@qq.com.
Thanks a lot!

**Comment by ggsDing** [comment]
Hi. You need to write a wrapper to get access to the SAM features. However, these features are with the spatial resolution of H/16*W/16. So in our practice, we did not achieve satisfactory results with the original version of SAM features.
However, it is possible to utilize also the SAM decoder to improve spatial accuracy. We did not implement that but you are welcome to try.
