### ISSUE TITLE
Samcd

### ISSUE THREAD

**Issue by JXBBBBB** [ggsDing/SAM-CD#2]
<img width="580" alt="05019507ead795540fdf29e58b9b47b" src="https://github.com/ggsDing/SAM-CD/assets/146403648/d8719abf-8240-4066-987d-e2170a6e7a8a">
这里显示的是results形式的输出，然后在下一步就报错。大佬这是咋回事啊

**Comment by ggsDing** [comment]
> <img alt="05019507ead795540fdf29e58b9b47b" width="580" src="https://user-images.githubusercontent.com/146403648/279912054-d8719abf-8240-4066-987d-e2170a6e7a8a.png"> 这里显示的是results形式的输出，然后在下一步就报错。大佬这是咋回事啊

需要修改ultralytics这个包，等我加个修改说明

**Comment by ggsDing** [comment]
check:
https://github.com/ggsDing/SAM-CD/blob/main/models/FastSAM/changes.rec
