### ISSUE TITLE
featsA = [] in pred_CD.py

### ISSUE THREAD

**Issue by Liuc-2022** [ggsDing/SAM-CD#20]
When debugging the code "pred_CD.py", a situation was encountered where featsA=[] and featsB=[], resulting in featA_s4=self Adapter4 (featsA [3]. clone()) reported an error "IndexError: list index out of range". How to solve this problem?

**Comment by ggsDing** [comment]
Check: https://github.com/ggsDing/SAM-CD/issues/4

Please modify the Ultralytics source files following the instructions at:
https://github.com/ggsDing/SAM-CD/blob/main/models/FastSAM/README.md
