### ISSUE TITLE
如何调整FastSAM第一层输出特征L1的大小

### ISSUE THREAD

**Issue by Liu-sunshine** [ggsDing/SAM-CD#23]
作者你好，你所提出的SAM-CD对遥感变化检测领域非常有意义。
我有一些问题想请教一下，论文中SAM-CD第一个特征层输出的特征L1为输入图像的1/4，我想将第一个特征层输出的特征L1改为输入图像的1/2。针对上述问题，在源码中，我应该如何更改。

**Comment by ggsDing** [comment]
您好。可以上采样，或者直接用第二个尺度特征。

**Comment by Liu-sunshine** [comment]
感谢您的回复。我想要调整网络输出的多尺度特征的大小，使得L1为输入图像的1/2，L2为输入图像的1/4，L3为输入图像的1/8，L4为输入图像的1/16。因此，可能需要更改网络结构初始阶段（输出L1特征之前的卷积阶段）的卷积步长，将步长为2改为步长为1。请问更改卷积步长的操作，在SAM-CD的源码中的哪一部分？

**Comment by DingLei14** [comment]
> 感谢您的回复。我想要调整网络输出的多尺度特征的大小，使得L1为输入图像的1/2，L2为输入图像的1/4，L3为输入图像的1/8，L4为输入图像的1/16。因此，可能需要更改网络结构初始阶段（输出L1特征之前的卷积阶段）的卷积步长，将步长为2改为步长为1。请问更改卷积步长的操作，在SAM-CD的源码中的哪一部分？

建议不要直接改SAM源码，因为和预训练的权重不对应，会影响效果。可在输入SAM之前额外添加卷积层进行调整。

**Comment by Liu-sunshine** [comment]
好哩，感谢您的解答。
