### ISSUE TITLE
WHU数据集的图片分辨率，数量和是否要crop增强，crop size的大小

### ISSUE THREAD

**Issue by yaohusama** [ggsDing/SAM-CD#24]
我想问一下，当WHU数据集输入SAM-CD网络时，WHU数据集的分辨率是多少呢？
我看这个仓库里提供的下载链接的WHU数据集划分的图是256x256的分辨率的，那是否网络输入图片分辨率就是256x256呢？那是否还要crop图增强，如果要crop图，crop size多大呢？
另外，我看下载链接里的WHU数据集的train文件夹，包括了val文件夹下的图片，这是正确的吗？论文里提到we divide the dataset into training, validation and test sets with 6096, 762 and 762 pairs of image patches (each with a spatial size of 256×256, respectively.
而我看提供下载链接里的whu数据集的val是743张图，train是6691张，test743张，为什么和论文里提到的数量不一致呢。

**Comment by DingLei14** [comment]
> 我想问一下，当WHU数据集输入SAM-CD网络时，WHU数据集的分辨率是多少呢？ 我看这个仓库里提供的下载链接的WHU数据集划分的图是256x256的分辨率的，那是否网络输入图片分辨率就是256x256呢？那是否还要crop图增强，如果要crop图，crop size多大呢？ 另外，我看下载链接里的WHU数据集的train文件夹，包括了val文件夹下的图片，这是正确的吗？论文里提到we divide the dataset into training, validation and test sets with 6096, 762 and 762 pairs of image patches (each with a spatial size of 256×256, respectively. 而我看提供下载链接里的whu数据集的val是743张图，train是6691张，test743张，为什么和论文里提到的数量不一致呢。

您好，感谢关注。
1.WHU-CD 的分辨率请查阅数据集发布说明。
2.本文未进行crop，仅使用了flip增强
3.本文实验设置沿用了其他文章的实验设置数据集也不是我们处理，只是为了便利查找，给出了网盘链接。实际实验的训练测试划分是按照论文的，把train目录的val图片删除即可。

**Comment by yaohusama** [comment]
谢谢。我用网盘链接里的WHU数据集跑了SAM-CD，没用crop增强，分辨率是256x256，只达到了截图里的指标。和论文里的相差很多，请问是因为levir cd数据集和whu数据集的训练超参不一样吗，比如学习率或者优化器的不同，epoch的不同吗？我该怎么复现出论文里的指标呢？或者可以提供whu数据集上的训练权重吗？我看仓库里目前只有levir cd数据集的训练权重。
![image](https://github.com/ggsDing/SAM-CD/assets/45895827/5f2d8741-1618-4eaf-9cb1-71b8090ca6af)

![image](https://github.com/ggsDing/SAM-CD/assets/45895827/c9b729d6-c1f9-44c6-b444-3c63b34ce638)

**Comment by DingLei14** [comment]
> 谢谢。我用网盘链接里的WHU数据集跑了SAM-CD，没用crop增强，分辨率是256x256，只达到了截图里的指标。和论文里的相差很多，请问是因为levir cd数据集和whu数据集的训练超参不一样吗，比如学习率或者优化器的不同，epoch的不同吗？我该怎么复现出论文里的指标呢？或者可以提供whu数据集上的训练权重吗？我看仓库里目前只有levir cd数据集的训练权重。 ![image](https://private-user-images.githubusercontent.com/45895827/339955603-5f2d8741-1618-4eaf-9cb1-71b8090ca6af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0Mjg4NTQsIm5iZiI6MTcxODQyODU1NCwicGF0aCI6Ii80NTg5NTgyNy8zMzk5NTU2MDMtNWYyZDg3NDEtMTYxOC00ZWFmLTljYjEtNzFiODA5MGNhNmFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE1VDA1MTU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2ZDAxZDE5NDg5NTRiODJlZTA2ODE4NmMzZDk4MjE2YzJmZTYzZGM5MGE1YmM1NWVlYjlmMGFiNGViNGZlNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yNxL2lGRp0O-598afR5Rp7koMPsulMWF2WZ7YtrE4jk)
> 
> ![image](https://private-user-images.githubusercontent.com/45895827/339955675-c9b729d6-c1f9-44c6-b444-3c63b34ce638.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0Mjg4NTQsIm5iZiI6MTcxODQyODU1NCwicGF0aCI6Ii80NTg5NTgyNy8zMzk5NTU2NzUtYzliNzI5ZDYtYzFmOS00NGM2LWI0NDQtM2M2M2IzNGNlNjM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE1VDA1MTU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhNjU0ZGMzMmQyNTQ2NTAyN2JmYzVmYzI1OTZkN2Y0ZGU3ZGFjM2E3ODk4YTRhOWI2ODNkYWY3MjgzZTcyMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rS5m3kNlTMmz0ZOeUVyo0W-zav-t_iuwr-8-quvO49E)

文章里的指标是mF1，之所以选取该指标也是沿用了其他文章的实验设置。
权重我近期整理下开放。

**Comment by yaohusama** [comment]
仓库里是levir cd的训练代码，那我用仓库的代码改跑WHU数据集只有95.62的mf1，而论文里报的是97.58的mF1，那这种差别如果不是因为随机性的话，那是不是因为某些训练超参不一样呢，可以告诉我是需要修改哪些超参来达到论文相近的指标吗？麻烦大佬了！
