### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by JoeNumberOne** [ggsDing/SAM-CD#25]
![image](https://github.com/ggsDing/SAM-CD/assets/34960932/df1485b1-dd17-4968-8ec5-655f2617ffb1)

line 177, in forward
    featA_s4 = self.Adapter4(featsA[3].clone().to(device1))
IndexError: list index out of range

when I run this program, this place shows the  list index out of range, I find the length is 3, I just don't figure out why, could you please help me ?

**Comment by JoeNumberOne** [comment]
solved

**Comment by kuaiqushangzixiba** [comment]
how too solve?

**Comment by 18810031387** [comment]
I have the same problem how to fix it。
![image](https://github.com/user-attachments/assets/be2f46d3-182e-44ef-aabd-b60df0aa170a)

**Comment by Plaitkol** [comment]
Hi! After modifying the Ultralytics source files, I still encountered the same issue. Could you please help me?
