### ISSUE TITLE
关于levir cd数据集的precision和recall指标和论文对不上的问题

### ISSUE THREAD

**Issue by yaohusama** [ggsDing/SAM-CD#26]
我用了您levir cd上公布的模型，inference的指标中mIoU，mF1，OA能对上，但是precsion和recall差了3个点及以上。
<img width="503" alt="5823a627d2da672e0a570a9694490b7" src="https://github.com/ggsDing/SAM-CD/assets/45895827/9585dde6-854a-4f81-91e5-43f71a82cdd6">
论文里的指标：
![image](https://github.com/ggsDing/SAM-CD/assets/45895827/2e112054-10dc-4607-b084-8b83faf145c2)

是论文里的precision和recall的计算方式和代码里的不同吗？不懂为什么用公布的模型得到的precision和recall和论文里的对不上。
谢谢。

**Comment by yaohusama** [comment]
我发现论文里的precision算的应该是前景和背景各自的precision，recall也类似。代码给的是算的前景的precision，是算的方式不同。那就没问题了，谢谢。

**Comment by DingLei14** [comment]
谢谢提醒。后续把指标和论文里统一一下。
