### ISSUE TITLE
'Result' object has no attribute 'clone'.

### ISSUE THREAD

**Issue by nononoyou** [ggsDing/SAM-CD#5]
在训练过程中报以下错误：
File "/SAM-CD/models/SAM_CD.py", line 165, in forward
    featA_s4 = self.Adapter4(featsA[3].clone())
  File "//anaconda3/envs/pytorch17/lib/python3.8/site-packages/ultralytics/yolo/utils/__init__.py", line 135, in __getattr__
    raise AttributeError(f"'{name}' object has no attribute '{attr}'. See valid attributes below.\n{self.__doc__}")
AttributeError: 'Results' object has no attribute 'clone'.
想问下作者在实现过程中是否遇见。想想！

**Comment by nononoyou** [comment]
谢谢 佬！弄好了。

**Comment by Notoriuosity** [comment]
现在那个注释不对了，应该如何解决呢

**Comment by Plaitkol** [comment]
> 现在那个注释不对了，应该如何解决呢

你好。 请问你解决了吗？
