### ISSUE TITLE
RuntimeError: shape '[1, 105, -1]' is invalid for input of size 10485760

### ISSUE THREAD

**Issue by TingFinn** [ggsDing/SAM-CD#6]
Hello, your work is very interesting. Thank you for the open source as well as the guide to use it. Although I have followed the [https://github.com/ggsDing/SAM-CD/blob/main/models/FastSAM/README.md](url)  , I am having some problems with it and I was wondering if it would be convenient for you to answer them. The questions are as follows:

  File "/anaconda3/envs/FastSAM/lib/python3.9/site-packages/ultralytics/nn/tasks.py", line 96, in _predict_once
    x = m(x)  # run
  File "/anaconda3/envs/FastSAM/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/anaconda3/envs/FastSAM/lib/python3.9/site-packages/ultralytics/nn/modules/head.py", line 94, in forward
    x = self.detect(self, x)
  File "/anaconda3/envs/FastSAM/lib/python3.9/site-packages/ultralytics/nn/modules/head.py", line 54, in forward
    x_cat = torch.cat([xi.view(shape[0], self.no, -1) for xi in x], 2)
  File "/anaconda3/envs/FastSAM/lib/python3.9/site-packages/ultralytics/nn/modules/head.py", line 54, in <listcomp>
    x_cat = torch.cat([xi.view(shape[0], self.no, -1) for xi in x], 2)
RuntimeError: shape '[1, 105, -1]' is invalid for input of size 10485760

**Comment by ggsDing** [comment]
Hi, thanks for your interest in this work.
Are you running your own dataset or you are testing the Levir-CD? From the feedback of other users, it will be ok if you modify the Ultralytics source files as instructed.

**Comment by TingFinn** [comment]
> Hi, thanks for your interest in this work. Are you running your own dataset or you are testing the Levir-CD? From the feedback of other users, it will be ok if you modify the Ultralytics source files as instructed.

I am using the LEVIR-CD dataset. And I am able to run train_SAM_CD.py or train_CD.py without any problems, but when I run pred_CD.py I get the above error.

**Comment by TingFinn** [comment]
> Hi, thanks for your interest in this work. Are you running your own dataset or you are testing the Levir-CD? From the feedback of other users, it will be ok if you modify the Ultralytics source files as instructed.

Thanks for the answer, problem solved. I made a mistake because I was using python 3.9 so I thought I didn't need to change [head.py.](https://github.com/ggsDing/SAM-CD/blob/main/models/FastSAM/README.md#find-anaconda_dirlibpython310site-packagesultralyticsnnmodulesheadpy)
