### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'sigmoid'

### ISSUE THREAD

**Issue by emilyemliyM** [ggsDing/SAM-CD#7]
![image](https://github.com/ggsDing/SAM-CD/assets/88700988/b89de267-0fef-4e7e-aade-aa8c96299571)

Do I need change the  output tuple  to  the outC only?

Thanks a lot.

**Comment by ggsDing** [comment]
Hi,
I don't quite get the problem. Did you change the training settings?

**Comment by tudoulei** [comment]
我也是一样的问题

**Comment by Zhugguanglei** [comment]
> Hi, I don't quite get the problem. Did you change the training settings?

我也是遇到了同样的问题

**Comment by supoman-lei** [comment]
> > Hi, I don't quite get the problem. Did you change the training settings?
> 
> 我也是遇到了同样的问题

我解决了这个问题，在pred_CD.py文件中，out接收了net返回的三个tensor，变成了一个touple类型，但在train_SAM_CD.py文件中net的返回值是通过三个变量`output, outA, outB = net(tensorA, tensorB)`来接受的，我用同样的方式修改代码后，代码就成功跑起来了 @ggsDing @emilyemliyM @tudoulei

**Comment by ggsDing** [comment]
> > > Hi, I don't quite get the problem. Did you change the training settings?
> > 
> > 
> > 我也是遇到了同样的问题
> 
> 我解决了这个问题，在pred_CD.py文件中，out接收了net返回的三个tensor，变成了一个touple类型，但在train_SAM_CD.py文件中net的返回值是通过三个变量`output, outA, outB = net(tensorA, tensorB)`来接收的，我用同样的方式修改代码后，代码就成功跑起来了 @ggsDing @emilyemliyM @tudoulei

谢谢，代码已更正 @tudoulei @supoman-lei @emilyemliyM

**Comment by sijie-Xu** [comment]
![1703643836327](https://github.com/ggsDing/SAM-CD/assets/122505422/6d7bd205-4cf6-4ac2-9973-ac34fec174c6)



> > > > Hi, I don't quite get the problem. Did you change the training settings?
> > > 
> > > 
> > > 我也是遇到了同样的问题
> > 
> > 
> > 我解决了这个问题，在pred_CD.py文件中，out接收了net返回的三个tensor，变成了一个touple类型，但在train_SAM_CD.py文件中net的返回值是通过三个变量`output, outA, outB = net(tensorA, tensorB)`来接收的，我用同样的方式修改代码后，代码就成功跑起来了 @ggsDing @emilyemliyM @tudoulei
> 
> 谢谢，代码已更正 @tudoulei @supoman-lei @emilyemliyM

更正后的代码依旧不能运行

**Comment by supoman-lei** [comment]
> ![1703643836327](https://private-user-images.githubusercontent.com/122505422/292943943-6d7bd205-4cf6-4ac2-9973-ac34fec174c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NTA2ODQsIm5iZiI6MTcwMzY1MDM4NCwicGF0aCI6Ii8xMjI1MDU0MjIvMjkyOTQzOTQzLTZkN2JkMjA1LTRjZjYtNGFjMi05OTczLWFjMzRmZWMxNzRjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyN1QwNDEzMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOTg3ZWM2ZGRiNmJjMWZjMTg1MzZiMjcwYmMzNDk2NDhjMjQ4YTlhZDM4ZWNhYTQyNzMxM2Q1YjU3YjIzYzY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SihMQ-tJdvlcwSlolK_iNoW_fKnS19M0cZAkKTRqfOo)
> 
> > > > > Hi, I don't quite get the problem. Did you change the training settings?
> > > > 
> > > > 
> > > > 我也是遇到了同样的问题
> > > 
> > > 
> > > 我解决了这个问题，在pred_CD.py文件中，out接收了net返回的三个tensor，变成了一个touple类型，但在train_SAM_CD.py文件中net的返回值是通过三个变量`output, outA, outB = net(tensorA, tensorB)`来接收的，我用同样的方式修改代码后，代码就成功跑起来了 @ggsDing @emilyemliyM @tudoulei
> > 
> > 
> > 谢谢，代码已更正 @tudoulei @supoman-lei @emilyemliyM
> 
> 更正后的代码依旧不能运行

作者更正错了两行代码：
`                     output = net(tensorA, tensorB)
                      output, _, _ = F.sigmoid(output)`
应该改为：
`                     output, _, _ = net(tensorA, tensorB)
                      output = F.sigmoid(output)`

**Comment by sijie-Xu** [comment]
> > ![1703643836327](https://private-user-images.githubusercontent.com/122505422/292943943-6d7bd205-4cf6-4ac2-9973-ac34fec174c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NTA2ODQsIm5iZiI6MTcwMzY1MDM4NCwicGF0aCI6Ii8xMjI1MDU0MjIvMjkyOTQzOTQzLTZkN2JkMjA1LTRjZjYtNGFjMi05OTczLWFjMzRmZWMxNzRjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyN1QwNDEzMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOTg3ZWM2ZGRiNmJjMWZjMTg1MzZiMjcwYmMzNDk2NDhjMjQ4YTlhZDM4ZWNhYTQyNzMxM2Q1YjU3YjIzYzY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SihMQ-tJdvlcwSlolK_iNoW_fKnS19M0cZAkKTRqfOo)
> > > > > > Hi, I don't quite get the problem. Did you change the training settings?
> > > > > 
> > > > > 
> > > > > 我也是遇到了同样的问题
> > > > 
> > > > 
> > > > 我解决了这个问题，在pred_CD.py文件中，out接收了net返回的三个tensor，变成了一个touple类型，但在train_SAM_CD.py文件中net的返回值是通过三个变量`output, outA, outB = net(tensorA, tensorB)`来接收的，我用同样的方式修改代码后，代码就成功跑起来了 @ggsDing @emilyemliyM @tudoulei
> > > 
> > > 
> > > 谢谢，代码已更正 @tudoulei @supoman-lei @emilyemliyM
> > 
> > 
> > 更正后的代码依旧不能运行
> 
> 作者更正错了两行代码： ` output = net(tensorA, tensorB) output, _, _ = F.sigmoid(output)` 应该改为： ` output, _, _ = net(tensorA, tensorB) output = F.sigmoid(output)`

非常感谢！可以运行了
